package org.eclipse.linuxtools.lttng.ui.views.histogram;

import org.eclipse.swt.events.ControlEvent;
import org.eclipse.swt.events.ControlListener;

/**
 * <b><u>HistogramCanvasControlListener</u></b>
 * <p>
 * Implementation of a ControlListener for the need of the HistogramCanvas
 * <p> 
 */
public class HistogramCanvasControlListener implements ControlListener {
	
	protected HistogramCanvas parentCanvas = null;
	
	/**
	 * HistogramCanvasControlListener constructor
	 * 
	 * @param newCanvas Related canvas
	 */
	public HistogramCanvasControlListener(HistogramCanvas newCanvas) {
		parentCanvas = newCanvas;
	}
	
	
	/**
	 * Method called when the canvas is moved.<p>
	 * 
	 * Just redraw the canvas...
	 * 
	 * @param event 	The controle event generated by the move.
	 */
	public void controlMoved(ControlEvent event) {
		parentCanvas.redraw();
	}
	
	/**
	 * Method called when the canvas is resized.<p>
	 * 
	 * We need to tell the content that the canvas size changed
	 * 
	 * @param event 	The control event generated by the resize.
	 */
	public void controlResized(ControlEvent event) {
		
		if ( (parentCanvas != null) && (parentCanvas.getHistogramContent() != null) ) {
			// Set the new canvas size
			parentCanvas.getHistogramContent().setCanvasWindowSize(parentCanvas.getSize().x);
		}
	}
}
